### ISSUE TITLE
Code for eval

### ISSUE THREAD

**Issue by tunglamlqddb** [HITsz-TMG/Ext-Sub#4]
Hi authors,
Thanks for sharing the code for the interesting paper.
I wonder if you could release the eval code, or tell us which repo you are using to eval?

Thank you

**Comment by YanshekWoo** [comment]
Thank you for your interest in our work. 
Our evaluation code is primarily located in the "[eval](https://github.com/HITsz-TMG/Ext-Sub/tree/main/eval)" folder. 
We are also considering gradually improving the corresponding evaluation scripts.

**Comment by YanshekWoo** [comment]
For the evaluation of TruthfulQA, you can refer to their [official repository](https://github.com/sylinrl/TruthfulQA). 

Our evaluation includes the following modifications to the official repository: 
(1) adjustments to the prompts for model input and output: [format_prompt](https://github.com/sylinrl/TruthfulQA/blob/fdd8ad1c0d00a478cf8b0bb41a3ad8378c16293b/truthfulqa/utilities.py#L22)
(2) support for model LoRA loading: [model loading in run_answers](https://github.com/sylinrl/TruthfulQA/blob/fdd8ad1c0d00a478cf8b0bb41a3ad8378c16293b/truthfulqa/models.py#L212), [model loading in run_probs](https://github.com/sylinrl/TruthfulQA/blob/fdd8ad1c0d00a478cf8b0bb41a3ad8378c16293b/truthfulqa/models.py#L274)

We can make the modified TruthfulQA evaluation repository publicly available in the future.

**Comment by tunglamlqddb** [comment]
Thank you for the reply. This helps a lot
